//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHARTDATA
    {
        public int ChartId { get; set; }
        public string DonorName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
        public string Department { get; set; }
        public string GL { get; set; }
    }
}
