//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CODES
    {
        public int CodeId { get; set; }
        public string Fund { get; set; }
        public string GL { get; set; }
        public string Department { get; set; }
        public string Program { get; set; }
        public string Grants { get; set; }
        public string Appeal { get; set; }
        public Nullable<int> DonationId { get; set; }
        public Nullable<int> DonorId { get; set; }
    
        public virtual DONATION DONATION1 { get; set; }
    }
}
