//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testDMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class CONTACT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTACT()
        {
            this.DONORs = new HashSet<DONOR>();
        }
        
        public int CONTACTID { get; set; }

        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:MM-dd-yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime DATEOF { get; set; }

        [Display(Name = "Type")]
        public string TYPEOF { get; set; }

        [Display(Name = "Method")]
        public string METHOD { get; set; }

        [Display(Name = "Subject")]
        public string SUBJECTOF { get; set; }

        [Display(Name = "Summary")]
        public string SUMMARY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONOR> DONORs { get; set; }
    }
}
