//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONATION()
        {
            this.FILES = new HashSet<FILES>();
        }
    
        public int DonationId { get; set; }
        public int DonorId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string TypeOf { get; set; }
        public Nullable<System.DateTime> DateRecieved { get; set; }
        public string GiftMethod { get; set; }
        public Nullable<System.DateTime> DateGiftMade { get; set; }
        public string GiftRestrictions { get; set; }
        public string Notes { get; set; }
        public string Fund { get; set; }
        public string GL { get; set; }
        public string Department { get; set; }
        public string Program { get; set; }
        public string GrantS { get; set; }
        public string Appeal { get; set; }
    
        public virtual DONOR DONOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FILES> FILES { get; set; }
    }
}
