//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testDMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    //using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class DONATION
    {
        public int DonationId { get; set; }

        public int DonorId { get; set; }

        [DataType(DataType.Currency), Display(Name = "Amount")]
        public decimal Amount { get; set; }

        [Display(Name = "Type")]
        public string TypeOf { get; set; }

        [DataType(DataType.Date),DisplayFormat(DataFormatString = "{0:MM-dd-yyyy}", ApplyFormatInEditMode = true), Display(Name = "Date Received")]
        public System.DateTime DateRecieved { get; set; }

        [Display(Name = "Method")]
        public string GiftMethod { get; set; }

        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:MM-dd-yyyy}", ApplyFormatInEditMode = true), Display(Name = "Date Made")]
        public System.DateTime DateGiftMade { get; set; }

        public Nullable<int> CodeId { get; set; }

        [Display(Name = "Image")]
        public byte[] ImageUpload { get; set; }

        [Display(Name = "Restrictions")]
        public string GiftRestrictions { get; set; }
    
        public virtual CODE CODE { get; set; }
        public virtual DONOR DONOR { get; set; }
    }
}
