//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONOR()
        {
            this.DONATIONs = new HashSet<DONATION>();
            this.RELATIVES = new HashSet<RELATIVE>();
        }
    
        public int DONORID { get; set; }
        public string FNAME { get; set; }
        public string MINIT { get; set; }
        public string LNAME { get; set; }
        public string TITLE { get; set; }
        public string SUFFIX { get; set; }
        public string EMAIL { get; set; }
        public string CELL { get; set; }
        public System.DateTime BIRTHDAY { get; set; }
        public string GENDER { get; set; }
        public Nullable<int> MARKERID { get; set; }
        public Nullable<int> CONTACTID { get; set; }
        public Nullable<int> COMPANYID { get; set; }
    
        public virtual COMPANY COMPANY { get; set; }
        public virtual CONTACT CONTACT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONATION> DONATIONs { get; set; }
        public virtual IDENTITYMARKER IDENTITYMARKER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RELATIVE> RELATIVES { get; set; }
    }
}
