//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testDMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class DONOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONOR()
        {
            this.DONATION = new HashSet<DONATION>();
            this.NOTES = new HashSet<NOTES>();
            this.RELATIVES = new HashSet<RELATIVES>();
        }
    
        public int DonorId { get; set; }
        [Display(Name = "First Name")]
        public string FName { get; set; }
        [Display(Name = "Initial")]
        public string Init { get; set; }
        [Display(Name = "Last Name")]
        public string LName { get; set; }
        public string Title { get; set; }
        public string Suffix { get; set; }
        public string Email { get; set; }
        public string Cell { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Gender { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> MarkerId { get; set; }
        public Nullable<int> ContactId { get; set; }
    
        public virtual COMPANY COMPANY { get; set; }
        public virtual CONTACT CONTACT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONATION> DONATION { get; set; }
        public virtual IDENTITYMARKER IDENTITYMARKER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTES> NOTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RELATIVES> RELATIVES { get; set; }
    }
}
