//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testDMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DonorManagementDatabaseEntities : DbContext
    {
        public DonorManagementDatabaseEntities()
            : base("name=DonorManagementDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<CODE> Code { get; set; }
        public virtual DbSet<COMPANY> Company { get; set; }
        public virtual DbSet<CONTACT> Contact { get; set; }
        public virtual DbSet<DONATION> Donation { get; set; }
        public virtual DbSet<DONOR> Donor { get; set; }
        public virtual DbSet<IDENTITYMARKER> IdentityMarker { get; set; }
        public virtual DbSet<RELATIVE> RELATIVES { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
        public virtual DbSet<NOTE> NOTES { get; set; }
    }
}
