//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTE
    {
        public int NOTEID { get; set; }
        public int DONORID { get; set; }
        public string NOTE1 { get; set; }
        public Nullable<System.DateTime> DATEMADE { get; set; }
    
        public virtual DONOR DONOR { get; set; }
    }
}
