//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTES
    {
        public int NoteId { get; set; }
        public int DonorId { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> DateMade { get; set; }
    
        public virtual DONOR DONOR { get; set; }
    }
}
